# Generated by Django 4.2.6 on 2023-10-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="key",
            name="key_index",
            field=models.CharField(
                db_index=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
