# Generated by Django 4.2.6 on 2023-10-31 12:38
import hashlib

from django.db import migrations


def update_key_indexed(apps, schema_editor):
    cls = apps.get_model("repo", "Key")
    for key in cls.objects.all():
        key.key_hash = hashlib.sha256(key.key.encode()).hexdigest()
        key.key_index = key.key[:255]
        key.save()


class Migration(migrations.Migration):

    dependencies = [
        ("repo", "0002_key_key_index"),
    ]

    operations = [
        migrations.RunPython(update_key_indexed),
    ]
