default:
  ALLOWED_HOSTS:
    - "*"
  DEBUG: false
  SECRET_KEY: null
  INSTALLED_APPS:
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.messages
    - django.contrib.staticfiles
    # 3d party Apps
    - countries_plus
    - languages_plus
    - debug_toolbar
    - djangoheads
    # Local Apps
    - repo
  MIDDLEWARE:
    - debug_toolbar.middleware.DebugToolbarMiddleware
    - django.middleware.security.SecurityMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware
  DEBUG_TOOLBAR_CONFIG:
    SHOW_TOOLBAR_CALLBACK: service.debug_toolbar.show_toolbar
  ROOT_URLCONF: service.urls
  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      DIRS:
        - /home/app/libs/service/templates
      APP_DIRS: true
      OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages
  WSGI_APPLICATION: service.wsgi.application
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3
  AUTH_PASSWORD_VALIDATORS:
    - NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
    - NAME: django.contrib.auth.password_validation.MinimumLengthValidator
    - NAME: django.contrib.auth.password_validation.CommonPasswordValidator
    - NAME: django.contrib.auth.password_validation.NumericPasswordValidator
  LANGUAGE_CODE: en-us
  TIME_ZONE: America/New_York
  USE_I18N: true
  USE_TZ: true
  STATIC_URL: /static/
  STATIC_ROOT: /var/www/static
  DEFAULT_AUTO_FIELD: django.db.models.BigAutoField
