# Generated by Django 4.2.6 on 2023-10-29 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("languages_plus", "0004_auto_20171214_0004"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoTranslateEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("alibaba", "alibaba"),
                            ("apertium", "apertium"),
                            ("argos", "argos"),
                            ("baidu", "baidu"),
                            ("bing", "bing"),
                            ("caiyun", "caiyun"),
                            ("cloudTranslation", "cloudTranslation"),
                            ("deepl", "deepl"),
                            ("elia", "elia"),
                            ("google", "google"),
                            ("iciba", "iciba"),
                            ("iflytek", "iflytek"),
                            ("iflyrec", "iflyrec"),
                            ("itranslate", "itranslate"),
                            ("judic", "judic"),
                            ("languageWire", "languageWire"),
                            ("lingvanex", "lingvanex"),
                            ("niutrans", "niutrans"),
                            ("mglip", "mglip"),
                            ("mirai", "mirai"),
                            ("modernMt", "modernMt"),
                            ("myMemory", "myMemory"),
                            ("papago", "papago"),
                            ("qqFanyi", "qqFanyi"),
                            ("qqTranSmart", "qqTranSmart"),
                            ("reverso", "reverso"),
                            ("sogou", "sogou"),
                            ("sysTran", "sysTran"),
                            ("tilde", "tilde"),
                            ("translateCom", "translateCom"),
                            ("translateMe", "translateMe"),
                            ("utibet", "utibet"),
                            ("volcEngine", "volcEngine"),
                            ("yandex", "yandex"),
                            ("yeekit", "yeekit"),
                            ("youdao", "youdao"),
                        ],
                        max_length=255,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
            options={"ordering": ("space", "name"),},
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "default_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="languages_plus.language",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField()),
                (
                    "key_hash",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="repo.space",
                    ),
                ),
            ],
            options={"unique_together": {("space", "key_hash")},},
        ),
        migrations.CreateModel(
            name="ImportI18Next",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="imports/%Y/%m/%d/")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="repo.group",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        default="en",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="languages_plus.language",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="repo.space",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="group",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="repo.space",
            ),
        ),
        migrations.CreateModel(
            name="AutoTranslate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="repo.autotranslateengine",
                    ),
                ),
                (
                    "from_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="languages_plus.language",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="repo.group",
                    ),
                ),
                (
                    "to_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="languages_plus.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                ("auto_translated", models.BooleanField(default=False)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phrases",
                        to="repo.key",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phrases",
                        to="languages_plus.language",
                    ),
                ),
            ],
            options={"unique_together": {("language", "key")},},
        ),
        migrations.CreateModel(
            name="KeyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="repo.group",
                    ),
                ),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="repo.key",
                    ),
                ),
            ],
            options={"unique_together": {("key", "group")},},
        ),
    ]
